### ISSUE TITLE
Is this library able to perform PSD2-compliant dialog initialization?

### ISSUE THREAD

**Issue by enniome** [raphaelm/python-fints#82] opened 2019-06-19 06:05 UTC
Is this library able to perform PSD2-compliant dialog initialization right now? While performing a dialog initialization I get a "3075 - Banking-Programm muss zum 14.09.2019 auf PSD2 umgestellt werden", which indicates it doesn't. What would be necessary to change that?

**Comment by raphaelm** [comment] 2019-06-19 06:57
No, the library is currently not. It's probably not too hard, since we already support TAN workflows and the required workflow is documented [here](https://www.hbci-zka.de/dokumente/spezifikation_deutsch/fintsv3/FinTS_3.0_Security_Sicherheitsverfahren_PINTAN_2018-02-23_final_version.pdf) in chapter B.4.3.

However, even though the spec is pretty good, it's hard and cumbersome to develop without having a bank who already provides an endpoint to test against.

**Comment by raphaelm** [comment] 2019-07-15 16:01
Let's close this as a duplicate of #72

**Closed by raphaelm** 2019-07-15 16:01 UTC
